package hpipe.decode

import Insts._
import chisel3._
import chisel3.util._
import chisel3.util.experimental.decode._
import hammer.UIntExt
import hpipe._

object RvcInst extends ChiselEnum {
  val C_ADDI4SPN, C_LW, C_SW                            = Value
  val C_ADDI, C_JAL, C_LI, C_LUI                        = Value
  val C_SRLI, C_SRAI, C_ANDI, C_SUB, C_XOR, C_OR, C_AND = Value
  val C_J, C_BEQZ, C_BNEZ                               = Value
  val C_SLLI, C_LWSP, C_MV, C_ADD, C_SWSP               = Value
  val C_INVALID                                         = Value
}

class RvcDecompressorIO(implicit p: HPipeParameters) extends Bundle {
  val in  = Input(UInt(16.W))
  val out = Output(Inst())
}

// Generated by LLM
class RvcDecompressor(implicit p: HPipeParameters) extends Module {
  val io = IO(new RvcDecompressorIO)
  val in = io.in

  // Register Addresses
  val rs1 = in(11, 7)
  val rs2 = in(6, 2)
  val rd  = in(11, 7)

  val rs1c = "b01".U(2.W) ## in(9, 7)
  val rs2c = "b01".U(2.W) ## in(4, 2)
  val rdc  = "b01".U(2.W) ## in(4, 2)

  val x0 = 0.U(5.W)
  val x1 = 1.U(5.W)
  val x2 = 2.U(5.W)

  // Immediates
  val addi4spnImm = Cat(in(10, 7), in(12, 11), in(5), in(6), 0.U(2.W))
  val lwImm       = Cat(in(5), in(12, 10), in(6), 0.U(2.W))
  val addiImm     = Cat(Fill(7, in(12)), in(6, 2))
  val jImm        = Cat(
    Fill(10, in(12)),
    in(8),
    in(10, 9),
    in(6),
    in(7),
    in(2),
    in(11),
    in(5, 3),
    0.U(1.W),
  )
  val addi16spImm =
    Cat(Fill(3, in(12)), in(4, 3), in(5), in(2), in(6), 0.U(4.W))
  val luiImm = Cat(Fill(15, in(12)), in(6, 2), 0.U(12.W))
  val bImm   = Cat(
    Fill(5, in(12)),
    in(6, 5),
    in(2),
    in(11, 10),
    in(4, 3),
    0.U(1.W),
  )
  val shamt   = Cat(in(12), in(6, 2))
  val lwspImm = Cat(in(3, 2), in(12), in(6, 4), 0.U(2.W))
  val swspImm = Cat(in(8, 7), in(12, 9), 0.U(2.W))

  // Opcodes
  val OP_IMM = "b0010011".U(7.W)
  val OP     = "b0110011".U(7.W)
  val LOAD   = "b0000011".U(7.W)
  val STORE  = "b0100011".U(7.W)
  val BRANCH = "b1100011".U(7.W)
  val JAL    = "b1101111".U(7.W)
  val JALR   = "b1100111".U(7.W)
  val LUI    = "b0110111".U(7.W)

  // Instruction Field Assembly
  def iType(imm: UInt, rs1: UInt, funct3: UInt, rd: UInt, opcode: UInt) =
    imm(11, 0) ## rs1 ## funct3 ## rd ## opcode
  def rType(
      funct7: UInt,
      rs2:    UInt,
      rs1:    UInt,
      funct3: UInt,
      rd:     UInt,
      opcode: UInt,
  ) = funct7 ## rs2 ## rs1 ## funct3 ## rd ## opcode
  def sType(
      imm:    UInt,
      rs2:    UInt,
      rs1:    UInt,
      funct3: UInt,
      opcode: UInt,
  ) = imm(11, 5) ## rs2 ## rs1 ## funct3 ## imm(4, 0) ## opcode
  def bType(
      imm:    UInt,
      rs2:    UInt,
      rs1:    UInt,
      funct3: UInt,
      opcode: UInt,
  ) =
    imm(12) ## imm(10, 5) ## rs2 ## rs1 ## funct3 ## imm(4, 1) ## imm(
      11,
    ) ## opcode
  def uType(imm: UInt, rd: UInt, opcode: UInt) = imm(31, 12) ## rd ## opcode
  def jType(imm: UInt, rd: UInt, opcode: UInt) =
    imm(20) ## imm(10, 1) ## imm(11) ## imm(19, 12) ## rd ## opcode

  // Quadrant 0
  val instAddi4spn =
    iType(Cat(0.U(2.W), addi4spnImm), x2, "b000".U(3.W), rdc, OP_IMM)
  val instLw = iType(Cat(0.U(25.W), lwImm), rs1c, "b010".U(3.W), rdc, LOAD)
  val instSw = sType(Cat(0.U(25.W), lwImm), rs2c, rs1c, "b010".U(3.W), STORE)

  // Quadrant 1
  val instAddi = iType(addiImm, rd, "b000".U(3.W), rd, OP_IMM)
  val instJal  = jType(jImm, x1, JAL)
  val instLi   = iType(addiImm, x0, "b000".U(3.W), rd, OP_IMM)
  val instLui  = Mux(
    rd === x2,
    iType(addi16spImm, x2, "b000".U(3.W), x2, OP_IMM),
    uType(luiImm, rd, LUI),
  )
  val srliImm  = Cat(0.U(6.W), shamt)
  val sraiImm  = srliImm | "b010000000000".U(12.W)
  val instSrli = iType(srliImm, rs1c, "b101".U(3.W), rs1c, OP_IMM)
  val instSrai = iType(sraiImm, rs1c, "b101".U(3.W), rs1c, OP_IMM)
  val instAndi = iType(addiImm, rs1c, "b111".U(3.W), rs1c, OP_IMM)
  val instSub  = rType("b0100000".U(7.W), rs2c, rs1c, "b000".U(3.W), rs1c, OP)
  val instXor  = rType("b0000000".U(7.W), rs2c, rs1c, "b100".U(3.W), rs1c, OP)
  val instOr   = rType("b0000000".U(7.W), rs2c, rs1c, "b110".U(3.W), rs1c, OP)
  val instAnd  = rType("b0000000".U(7.W), rs2c, rs1c, "b111".U(3.W), rs1c, OP)
  val instJ    = jType(jImm, x0, JAL)
  val instBeqz = bType(bImm, x0, rs1c, "b000".U(3.W), BRANCH)
  val instBnez = bType(bImm, x0, rs1c, "b001".U(3.W), BRANCH)

  // Quadrant 2
  val slliImm  = Cat(0.U(6.W), shamt)
  val instSlli = iType(slliImm, rd, "b001".U(3.W), rd, OP_IMM)
  val instLwsp = iType(Cat(0.U(24.W), lwspImm), x2, "b010".U(3.W), rd, LOAD)
  val instMv   = Mux(
    rs2 === x0,
    iType(0.U(12.W), rs1, "b000".U(3.W), x0, JALR), // C.JR
    rType("b0000000".U(7.W), rs2, x0, "b000".U(3.W), rd, OP),
  )
  val instAdd = Mux(
    rs2 === x0,
    Mux(
      rs1 === x0,
      "h00100073".U(32.W),                           // C.EBREAK
      iType(0.U(12.W), rs1, "b000".U(3.W), x1, JALR), // C.JALR
    ),
    rType("b0000000".U(7.W), rs2, rd, "b000".U(3.W), rd, OP),
  )
  val instSwsp = sType(Cat(0.U(24.W), swspImm), rs2, x2, "b010".U(3.W), STORE)

  // Decode compressed instruction
  val table = TruthTable(
    Seq(
      InstCs.C_ADDI4SPN -> BitPat(RvcInst.C_ADDI4SPN),
      InstCs.C_LW       -> BitPat(RvcInst.C_LW),
      InstCs.C_SW       -> BitPat(RvcInst.C_SW),
      InstCs.C_ADDI     -> BitPat(RvcInst.C_ADDI),
      InstCs.C_JAL      -> BitPat(RvcInst.C_JAL),
      InstCs.C_LI       -> BitPat(RvcInst.C_LI),
      InstCs.C_LUI      -> BitPat(RvcInst.C_LUI),
      InstCs.C_SRLI     -> BitPat(RvcInst.C_SRLI),
      InstCs.C_SRAI     -> BitPat(RvcInst.C_SRAI),
      InstCs.C_ANDI     -> BitPat(RvcInst.C_ANDI),
      InstCs.C_SUB      -> BitPat(RvcInst.C_SUB),
      InstCs.C_XOR      -> BitPat(RvcInst.C_XOR),
      InstCs.C_OR       -> BitPat(RvcInst.C_OR),
      InstCs.C_AND      -> BitPat(RvcInst.C_AND),
      InstCs.C_J        -> BitPat(RvcInst.C_J),
      InstCs.C_BEQZ     -> BitPat(RvcInst.C_BEQZ),
      InstCs.C_BNEZ     -> BitPat(RvcInst.C_BNEZ),
      InstCs.C_SLLI     -> BitPat(RvcInst.C_SLLI),
      InstCs.C_LWSP     -> BitPat(RvcInst.C_LWSP),
      InstCs.C_MV       -> BitPat(RvcInst.C_MV),
      InstCs.C_ADD      -> BitPat(RvcInst.C_ADD),
      InstCs.C_SWSP     -> BitPat(RvcInst.C_SWSP),
    ),
    BitPat(RvcInst.C_INVALID),
  )
  val decoded = decoder(in, table)

  io.out := MuxLookup(decoded, 0.U(32.W))(
    Seq(
      RvcInst.C_ADDI4SPN.asUInt -> instAddi4spn,
      RvcInst.C_LW.asUInt       -> instLw,
      RvcInst.C_SW.asUInt       -> instSw,
      RvcInst.C_ADDI.asUInt     -> instAddi,
      RvcInst.C_JAL.asUInt      -> instJal,
      RvcInst.C_LI.asUInt       -> instLi,
      RvcInst.C_LUI.asUInt      -> instLui,
      RvcInst.C_SRLI.asUInt     -> instSrli,
      RvcInst.C_SRAI.asUInt     -> instSrai,
      RvcInst.C_ANDI.asUInt     -> instAndi,
      RvcInst.C_SUB.asUInt      -> instSub,
      RvcInst.C_XOR.asUInt      -> instXor,
      RvcInst.C_OR.asUInt       -> instOr,
      RvcInst.C_AND.asUInt      -> instAnd,
      RvcInst.C_J.asUInt        -> instJ,
      RvcInst.C_BEQZ.asUInt     -> instBeqz,
      RvcInst.C_BNEZ.asUInt     -> instBnez,
      RvcInst.C_SLLI.asUInt     -> instSlli,
      RvcInst.C_LWSP.asUInt     -> instLwsp,
      RvcInst.C_MV.asUInt       -> instMv,
      RvcInst.C_ADD.asUInt      -> instAdd,
      RvcInst.C_SWSP.asUInt     -> instSwsp,
    ),
  )
}
