#!/bin/sh

echo -e "\033[36m\033[1mChecking Format...\033[0m"
./mill _.checkFormat
if [ $? -eq 1 ]; then
    echo -e "\033[31mFormat Check \033[1mFAILED\033[0m"
    exit 1
fi

echo -e "\033[36m\033[1mChecking Code Style...\033[0m"
java -jar src/main/resources/scalastyle.jar -c .scalastyle.xml src
if [ $? -eq 1 ]; then
    echo -e "\033[31mCode Style Check \033[1mFAILED\033[0m"
    exit 1
fi

echo -e "\033[32m\033[1mCode Check PASSED\033[0m"