#!/bin/sh

git stash push -k -u -m "pre-commit-format-check" --quiet

echo -e "\033[36m\033[1mChecking Format...\033[0m"
./mill _.checkFormat
if [ $? -eq 1 ]; then
    echo -e "\033[31mFormat Check \033[1mFAILED\033[0m"
    git stash pop --quiet
    exit 1
fi

git stash pop --quiet

echo -e "\033[32m\033[1mCode Check PASSED\033[0m"