package hpipe

import chisel3._
import chisel3.simulator.scalatest.ChiselSim
import hammer.test.Sim
import hammer.test.Test
import hpipe.decode.RvcDecompressor
import org.scalatest.freespec.AnyFreeSpec
import org.scalatest.matchers.must.Matchers

// Generated by LLM
class RvcSpec extends AnyFreeSpec with Matchers with ChiselSim {

  // Each pair is (compressed, expanded), generated with
  //   riscv64-unknown-elf-as -march=rv32imc -mabi=ilp32
  //   riscv64-unknown-elf-as -march=rv32im   -mabi=ilp32
  val cases = Seq(
    "C.ADDI4SPN" -> (0x0028 -> 0x00810513L),
    "C.LW"       -> (0x41c8 -> 0x0045a503L),
    "C.SW"       -> (0xc1c8 -> 0x00a5a223L),
    "C.JAL"      -> (0x2021 -> 0x008000efL),
    "C.J"        -> (0xa021 -> 0x0080006fL),
    "C.LI"       -> (0x4515 -> 0x00500513L),
    "C.LUI"      -> (0x6505 -> 0x00001537L),
    "C.ADDI"     -> (0x0515 -> 0x00550513L),
    "C.ADDI16SP" -> (0x6141 -> 0x01010113L),
    "C.SRLI"     -> (0x810d -> 0x00355513L),
    "C.SRAI"     -> (0x850d -> 0x40355513L),
    "C.ANDI"     -> (0x890d -> 0x00357513L),
    "C.SUB"      -> (0x8d0d -> 0x40b50533L),
    "C.XOR"      -> (0x8d2d -> 0x00b54533L),
    "C.OR"       -> (0x8d4d -> 0x00b56533L),
    "C.AND"      -> (0x8d6d -> 0x00b57533L),
    "C.SLLI"     -> (0x050e -> 0x00351513L),
    "C.LWSP"     -> (0x4512 -> 0x00412503L),
    "C.SWSP"     -> (0xc22a -> 0x00a12223L),
    "C.MV"       -> (0x852e -> 0x00b00533L),
    "C.ADD"      -> (0x952e -> 0x00b50533L),
    "C.JR"       -> (0x8502 -> 0x00050067L),
    "C.JALR"     -> (0x9502 -> 0x000500e7L),
    "C.BEQZ"     -> (0xc501 -> 0x00050463L),
    "C.BNEZ"     -> (0xe501 -> 0x00051463L),
    "C.NOP"      -> (0x0001 -> 0x00000013L),
    "C.EBREAK"   -> (0x9002 -> 0x00100073L),
  )

  "RvcDecompressor should expand all RV32C instructions" in
    Sim(new RvcDecompressor()(HPipeParameters())) { dut =>
      Test("all", dut) { dut =>
        val failures = cases.flatMap { case (name, (comp, exp)) =>
          dut.io.in.poke(comp.U)
          val obs = dut.io.out.peek().litValue
          Option.when(obs != BigInt(exp)) {
            f"$name: 0x$comp%04x -> 0x$obs%08x (expected 0x$exp%08x)"
          }
        }
        if (failures.nonEmpty) fail(failures.mkString("\n"))
      }
    }
}
