name: rtl release

on:
 push:
   tags:
     - 'v*'
jobs:
 release:
   runs-on: ubuntu-latest
   steps:
    - name: Checkout
      uses: actions/checkout@v6
      with:
        submodules: 'recursive'
    - name: Cache Scala
      uses: coursier/cache-action@v6
    - name: Build
      run: |
        make verilog
        mv build hpipe_${{ github.ref_name }}
        tar -cvzf hpipe_${{ github.ref_name }}.tar.gz hpipe_${{ github.ref_name }}
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        generate_release_notes: true
        files: hpipe_${{ github.ref_name }}.tar.gz
        token: ${{ secrets.RELEASE }}