name: rv-test

on:
  push:
    tags: ['*']
    branches: ['main']
  pull_request:
  workflow_dispatch:

jobs:
  rv:
    name: rv-env
    runs-on: ubuntu-latest
    steps:
      - name: Setup RISCV GNU Toolchain
        uses: Hamster5295/riscv-toolchain-setup@v2
        with:
          version: '2026.03.28'
          arch: riscv64
          libc: elf
          compiler: gcc
          os: ubuntu-24.04
